#!/usr/bin/env bash
# Script that configures an Ubuntu server while changing localhost and facebook IP

# Completely cleaning host file, except localhost ip
sudo sh -c 'echo "127.0.0.1 localhost" > /etc/hosts'

# Modifying already exising IP of localhost
sudo sed -i 's/127.0.0.1        localhost/127.0.0.2 localhost/' /etc/hosts

# Add facebook specific IP
echo "8.8.8.8        facebook.com" | sudo tee -a /etc/hosts > /dev/null

# Display the updated hosts file
echo "Updated /etc/hosts:"
cat /etc/hosts
